"use client"

import type React from "react"

import { createContext, useContext, useState } from "react"

type Language = "en" | "fr"

type LanguageProviderProps = {
  children: React.ReactNode
}

type LanguageProviderState = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Auth
    "auth.signIn": "Sign In",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.welcome": "Welcome back",
    "auth.subtitle": "Enter your credentials to access your account",
    "auth.loggingIn": "Logging in...",
     "auth.loginFailed": "Login failed.",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "Users",
    "nav.transactions": "Transactions",
    "nav.logout": "Logout",
    "nav.register": "Register",
    "nav.userList": "User List",
    // Added for new sidebar buttons
    "nav.country": "Country",
    "nav.countryList": "Country List",
    "nav.countryCreate": "Create Country",
    "nav.network": "Network",
    "nav.networkList": "Network List",
    "nav.networkCreate": "Create Network",
    "nav.devices": "Devices",
    "nav.devicesList": "Devices List",
    "nav.phoneNumbers": "Phone Numbers",
    "nav.smsLogs": "SMS Logs",
    "nav.fcmLogs": "FCM Logs",
    "nav.networkConfig": "Network Config",
    "nav.networkConfigList": "Network Config List",
    "nav.networkConfigCreate": "Create Network Config",
    "nav.remoteCommand": "Remote Command",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.adminDashboard": "Admin Dashboard",
    "dashboard.liveOverview": "Live overview of your platform",
    "dashboard.activeUsers": "Active Users",
    "dashboard.activeTasks": "Active Tasks",
    "dashboard.pendingCodes": "Pending Codes",
    "dashboard.async": "Async",
    "dashboard.logging": "Logging",
    "dashboard.enabled": "Enabled",
    "dashboard.disabled": "Disabled",
    "dashboard.email": "Email",
    "dashboard.sms": "SMS",
    "dashboard.userTaskActivity": "User & Task Activity",
    "dashboard.liveActivityFeed": "Live Activity Feed",
    "dashboard.users": "Users",
    "dashboard.tasks": "Tasks",
    "dashboard.failedToLoadStats": "Failed to load dashboard stats",
    "dashboard.totalUsers": "Total Users",
    "dashboard.totalTransactions": "Total Transactions",
    "dashboard.recentActivity": "Recent User Activity",
    "dashboard.userGrowth": "User Growth",
    "dashboard.taskStats": "Task Stats",
    "dashboard.scheduledTasks": "Scheduled Tasks",
    "dashboard.reservedTasks": "Reserved Tasks",
    "dashboard.userStats": "User Stats",
    "dashboard.pendingUsers": "Pending Users",
    "dashboard.verifiedUsers": "Verified Users",
    "dashboard.usersRegisteredToday": "Users Registered Today",
    "dashboard.usersRegisteredWeek": "Users Registered This Week",
    "dashboard.codeStats": "Code Stats",
    "dashboard.pendingPasswordReset": "Pending Password Reset",
    "dashboard.pendingEmailVerification": "Pending Email Verification",
    "dashboard.pendingPhoneVerification": "Pending Phone Verification",
    "dashboard.notificationInfo": "Notification Info",
    "dashboard.emailService": "Email Service",
    "dashboard.smsService": "SMS Service",
    "dashboard.asyncEnabled": "Async Enabled",
    "dashboard.loggingEnabled": "Logging Enabled",
    "dashboard.timestamp": "Timestamp",
    "dashboard.authError": "Authentication Error",
    "dashboard.showOnlyActiveUsers": "Show only active users",

    // Users
    "users.title": "Users",
    "users.search": "Search users...",
    "users.name": "Name",
    "users.email": "Email",
    "users.status": "Status",
    "users.createdAt": "Created At",
    "users.active": "Active",
    "users.inactive": "Inactive",
    "users.pending": "Pending",
    "users.allStatuses": "All Statuses",
    "users.phone": "Phone",
    "users.emailVerified": "Email Verified",
    "users.phoneVerified": "Phone Verified",
    "users.lastLogin": "Last Login",
    "users.details": "Details",
    "users.isActive": "Is Active",
    "users.uid": "UID",
    "users.verifyEmail": "Verify Email",
    "users.verifyPhone": "Verify Phone",
    "users.contactMethod": "Contact Method",
    "users.viewType": "View Type",
    "users.pendingUsers": "Pending Users",
    "users.allUsers": "All Users",
    "users.showingResults": "Showing {start} to {end} of {total} results",
    "users.pageOf": "Page {current} of {total}",
    "users.sendCode": "Send Code",
    "users.verifyCode": "Verify Code",
    "users.resendCode": "Resend Code",
    "users.verificationCode": "Verification Code",
    "users.enterVerificationCode": "Enter verification code",
    "users.codeSent": "Code sent successfully",
    "users.verificationSuccess": "Verification successful",
    "users.enterIdentifierToSendCode": "Enter the {type} to send verification code",
    "users.enterCodeSentTo": "Enter the verification code sent to {identifier}",
    "users.enterEmail": "Enter email",
    "users.enterPhone": "Enter phone number",
    "users.sending": "Sending...",
    "users.verifying": "Verifying...",
    // Activation/Deactivation
    "users.activate": "Activate",
    "users.deactivate": "Deactivate",
    "users.activating": "Activating...",
    "users.deactivating": "Deactivating...",
    "users.activated": "User activated",
    "users.deactivated": "User deactivated",
    "users.activationFailed": "Failed to activate user",
    "users.deactivationFailed": "Failed to deactivate user",
    "users.userActivatedSuccessfully": "User activated successfully",
    "users.userDeactivatedSuccessfully": "User deactivated successfully",
    // Verification toggle
    "users.unverifyEmail": "Unverify Email",
    "users.unverifyPhone": "Unverify Phone",
    "users.emailUnverifiedSuccessfully": "User email unverified successfully",
    "users.phoneUnverifiedSuccessfully": "User phone unverified successfully",
    "users.confirmVerifyEmail": "Are you sure you want to verify this user's email?",
    "users.confirmUnverifyEmail": "Are you sure you want to unverify this user's email?",
    "users.confirmVerifyPhone": "Are you sure you want to verify this user's phone?",
    "users.confirmUnverifyPhone": "Are you sure you want to unverify this user's phone?",

    "users.confirmActivateTitle": "Activate User",
    "users.confirmDeactivateTitle": "Deactivate User",
    "users.confirmActivateText": "Are you sure that you want to activate user?",
    "users.confirmDeactivateText": "Are you sure that you want to deactivate user?",

    // Transactions
    "transactions.title": "Transactions",
    "transactions.amount": "Amount",
    "transactions.user": "User",
    "transactions.date": "Date",
    "transactions.type": "Type",
    "transactions.status": "Status",
    "transactions.deposit": "Deposit",
    "transactions.withdrawal": "Withdrawal",
    "transactions.transfer": "Transfer",
    "transactions.completed": "Completed",
    "transactions.pending": "Pending",
    "transactions.failed": "Failed",
    "transactions.sentToUser": "Sent to User",
    "transactions.actions": "Actions",
    "transactions.searchByUser": "Search by user...",
    "transactions.allStatuses": "All Statuses",
    "transactions.allTypes": "All Types",
    "transactions.noTransactionsFound": "No transactions found.",
    "transactions.edit": "Edit",
    "transactions.delete": "Delete",
    "transactions.deleteTransaction": "Delete Transaction",
    "transactions.deleteConfirmation": "Are you sure you want to delete this transaction? This action cannot be undone.",
    "transactions.cancel": "Cancel",
    "transactions.editTransaction": "Edit Transaction",
    "transactions.updateTransactionDetails": "Update the transaction details below.",
    "transactions.externalTransactionId": "External Transaction ID",
    "transactions.balanceBefore": "Balance Before",
    "transactions.balanceAfter": "Balance After",
    "transactions.fees": "Fees",
    "transactions.confirmationMessage": "Confirmation Message",
    "transactions.rawSms": "Raw SMS",
    "transactions.completedAt": "Completed At",
    "transactions.errorMessage": "Error Message",
    "transactions.saving": "Saving...",
    "transactions.saveChanges": "Save Changes",
    "transactions.failedToLoad": "Failed to load transactions",
    "transactions.failedToUpdate": "Failed to update transaction.",
    "transactions.failedToDelete": "Could not delete transaction.",
    "transactions.transactionUpdated": "Transaction updated",
    "transactions.transactionUpdatedSuccess": "The transaction was updated successfully.",
    "transactions.transactionDeleted": "Transaction deleted",
    "transactions.transactionDeletedSuccess": "The transaction was deleted successfully.",
    "transactions.deleteFailed": "Delete failed",
    "transactions.showingResults": "Showing {start} to {end} of {total} results",
    "transactions.pageOf": "Page {current} of {total}",
    "transactions.recipientName": "Recipient Name",
    "transactions.recipientPhone": "Recipient Phone",
    "transactions.reference": "Reference",
    "transactions.network": "Network",
    "transactions.createdAt": "Created At",

    // Common
    "common.previous": "Previous",
    "common.next": "Next",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.actions": "Actions",
    "common.loading": "Loading...",
    "common.yes": "Yes",
    "common.close": "Close",
    "common.cancel": "Cancel",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.all": "All",
    "common.ok": "OK",
    "common.save": "Save",
    "common.errorOccurred": "An error occurred",
    "common.retry": "Retry",
    "common.retrying": "Retrying...",
    "common.dismiss": "Dismiss",

    // Registration Form
    "register.title": "Register New User",
    "register.firstName": "First Name",
    "register.lastName": "Last Name",
    "register.email": "Email",
    "register.phone": "Phone",
    "register.password": "Password",
    "register.passwordConfirm": "Confirm Password",
    "register.submit": "Register User",
    "register.success": "User registered successfully!",
    "register.failed": "Registration failed.",
    "register.passwordsNoMatch": "Passwords do not match.",
    "register.networkError": "Network error.",
    "register.registering": "Registering...",

    // Network Config
    "networkConfig.title": "Network Configuration",
    "networkConfig.list": "Network Configuration List",
    "networkConfig.create": "Create Network Configuration",
    "networkConfig.edit": "Edit Network Configuration",
    "networkConfig.add": "Add Network Config",
    "networkConfig.networkName": "Network Name",
    "networkConfig.status": "Status",
    "networkConfig.ussdCommands": "USSD Commands",
    "networkConfig.smsKeywords": "SMS Keywords",
    "networkConfig.errorKeywords": "Error Keywords",
    "networkConfig.settings": "Settings",
    "networkConfig.actions": "Actions",
    "networkConfig.active": "Active",
    "networkConfig.inactive": "Inactive",
    "networkConfig.editButton": "Edit",
    "networkConfig.network": "Network",
    "networkConfig.selectNetwork": "Select a network",
    "networkConfig.balanceCommand": "Balance Command",
    "networkConfig.depositCommand": "Deposit Command",
    "networkConfig.withdrawalCommand": "Withdrawal Command",
    "networkConfig.balanceKeywords": "Balance Keywords (comma-separated)",
    "networkConfig.depositKeywords": "Deposit Keywords (comma-separated)",
    "networkConfig.withdrawalKeywords": "Withdrawal Keywords (comma-separated)",
    "networkConfig.errorKeywordsInput": "Error Keywords (comma-separated)",
    "networkConfig.customSettings": "Custom Settings",
    "networkConfig.timeout": "Timeout (seconds)",
    "networkConfig.maxRetries": "Max Retries",
    "networkConfig.autoConfirm": "Auto Confirm",
    "networkConfig.maxRetriesLabel": "Max Retries:",
    "networkConfig.timeoutLabel": "Timeout:",
    "networkConfig.autoConfirmLabel": "Auto Confirm:",
    "networkConfig.creating": "Creating...",
    "networkConfig.saving": "Saving...",
    "networkConfig.saveChanges": "Save Changes",
    "networkConfig.cancel": "Cancel",
    "networkConfig.failedToLoad": "Failed to load network configurations",
    "networkConfig.failedToCreate": "Failed to create network configuration",
    "networkConfig.failedToUpdate": "Failed to update network configuration",
    "networkConfig.failedToLoadNetworks": "Failed to load networks",
    "networkConfig.errorLoading": "Error Loading Network Configurations",

    // Country
    "country.title": "Country",
    "country.list": "Country List",
    "country.create": "Create Country",
    "country.edit": "Edit Country",
    "country.add": "Add Country",
    "country.name": "Name",
    "country.code": "Code",
    "country.status": "Status",
    "country.actions": "Actions",
    "country.active": "Active",
    "country.inactive": "Inactive",
    "country.editButton": "Edit",
    "country.failedToLoad": "Failed to load countries",
    "country.failedToCreate": "Failed to create country",
    "country.failedToUpdate": "Failed to update country",
    "country.creating": "Creating...",
    "country.saving": "Saving...",
    "country.loading": "Loading...",
    "country.errorLoading": "Error Loading Countries",

    // Network
    "network.title": "Network",
    "network.list": "Network List",
    "network.create": "Create Network",
    "network.edit": "Edit Network",
    "network.add": "Add Network",
    "network.name": "Name",
    "network.code": "Code",
    "network.country": "Country",
    "network.status": "Status",
    "network.actions": "Actions",
    "network.active": "Active",
    "network.inactive": "Inactive",
    "network.editButton": "Edit",
    "network.ussdBaseCode": "USSD Base Code",
    "network.selectCountry": "Select a country",
    "network.creating": "Creating...",
    "network.saving": "Saving...",
    "network.save": "Save",
    "network.cancel": "Cancel",
    "network.failedToLoad": "Failed to load networks",
    "network.failedToCreate": "Failed to create network",
    "network.failedToUpdate": "Failed to update network",
    "network.failedToLoadCountries": "Failed to load countries",
    "network.loading": "Loading...",
    "network.errorLoading": "Error Loading Networks",

    // Devices
    "devices.title": "Devices",
    "devices.list": "Devices List",
    "devices.failedToLoad": "Failed to load devices",
    "devices.success": "Devices loaded successfully",
    "devices.loadedSuccessfully": "Devices loaded successfully",
    "devices.deviceId": "Device ID",
    "devices.name": "Name",
    "devices.status": "Status",
    "devices.lastSync": "Last Sync",
    "devices.actions": "Actions",
    "devices.noActionsAvailable": "No actions available",
    "devices.errorLoading": "Error Loading Devices",

    // Phone Numbers
    "phoneNumbers.title": "Phone Numbers",
    "phoneNumbers.list": "Phone Numbers List",
    "phoneNumbers.failedToLoad": "Failed to load phone numbers",
    "phoneNumbers.phoneNumber": "Phone Number",
    "phoneNumbers.network": "Network",
    "phoneNumbers.fullName": "Full Name",
    "phoneNumbers.errorLoading": "Error Loading Phone Numbers",

    // SMS Logs
    "smsLogs.title": "SMS Logs",
    "smsLogs.list": "SMS Logs List",
    "smsLogs.failedToLoad": "Failed to load SMS logs",
    "smsLogs.sender": "Sender",
    "smsLogs.content": "Content",
    "smsLogs.receivedAt": "Received At",
    "smsLogs.type": "Type",
    "smsLogs.copy": "Copy",
    "smsLogs.copied": "Copied!",
    "smsLogs.errorLoading": "Error Loading SMS Logs",

    // FCM Logs
    "fcmLogs.title": "FCM Logs",
    "fcmLogs.list": "FCM Logs List",
    "fcmLogs.failedToLoad": "Failed to load FCM logs",
    "fcmLogs.messageTitle": "Title",
    "fcmLogs.body": "Body",
    "fcmLogs.deviceId": "Device ID",
    "fcmLogs.createdAt": "Created At",
    "fcmLogs.copy": "Copy",
    "fcmLogs.copied": "Copied!",
    "fcmLogs.errorLoading": "Error Loading FCM Logs",

    // Remote Command
    "remoteCommand.title": "Remote Command",
    "remoteCommand.create": "Create Remote Command",
    "remoteCommand.failedToCreate": "Failed to create remote command",
    "remoteCommand.command": "Command",
    "remoteCommand.deviceId": "Device ID",
    "remoteCommand.parameters": "Parameters (JSON)",
    "remoteCommand.priority": "Priority",
    "remoteCommand.sending": "Sending...",
    "remoteCommand.sendCommand": "Send Command",
    "remoteCommand.parametersMustBeValidJson": "Parameters must be valid JSON",
    "remoteCommand.commandSentSuccessfully": "Command sent successfully",
    "remoteCommand.selectDeviceId": "Select a device",

    // Common additional
    "common.no": "No",
    "common.failedToLoad": "Failed to load data",
    "common.failedToCreate": "Failed to create",
    "common.failedToUpdate": "Failed to update",
    "common.failedToDelete": "Failed to delete",
  },
  fr: {
    // Auth
    "auth.signIn": "Se connecter",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.rememberMe": "Se souvenir de moi",
    "auth.forgotPassword": "Mot de passe oublié?",
    "auth.welcome": "Bon retour",
    "auth.subtitle": "Entrez vos identifiants pour accéder à votre compte",
    "auth.loggingIn": "Connexion...",
    "auth.loginFailed": "Échec de la connexion.",

    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.users": "Utilisateurs",
    "nav.transactions": "Transactions",
    "nav.logout": "Déconnexion",
    "nav.register": "Enregistrer",
    "nav.userList": "Liste des utilisateurs",
    // Added for new sidebar buttons
    "nav.country": "Pays",
    "nav.countryList": "Liste des pays",
    "nav.countryCreate": "Créer un pays",
    "nav.network": "Réseau",
    "nav.networkList": "Liste des réseaux",
    "nav.networkCreate": "Créer un réseau",
    "nav.devices": "Appareils",
    "nav.devicesList": "Liste des appareils",
    "nav.phoneNumbers": "Numéros de téléphone",
    "nav.smsLogs": "Journaux SMS",
    "nav.fcmLogs": "Journaux FCM",
    "nav.networkConfig": "Configuration réseau",
    "nav.networkConfigList": "Liste des configurations réseau",
    "nav.networkConfigCreate": "Créer une configuration réseau",
    "nav.remoteCommand": "Commande à distance",

    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.adminDashboard": "Tableau de bord administrateur",
    "dashboard.liveOverview": "Aperçu en direct de votre plateforme",
    "dashboard.activeUsers": "Utilisateurs actifs",
    "dashboard.activeTasks": "Tâches actives",
    "dashboard.pendingCodes": "Codes en attente",
    "dashboard.async": "Asynchrone",
    "dashboard.logging": "Journalisation",
    "dashboard.enabled": "Activé",
    "dashboard.disabled": "Désactivé",
    "dashboard.email": "Email",
    "dashboard.sms": "SMS",
    "dashboard.userTaskActivity": "Activité utilisateur et tâches",
    "dashboard.liveActivityFeed": "Flux d'activité en direct",
    "dashboard.users": "Utilisateurs",
    "dashboard.tasks": "Tâches",
    "dashboard.failedToLoadStats": "Échec du chargement des statistiques du tableau de bord",
    "dashboard.totalUsers": "Total Utilisateurs",
    "dashboard.totalTransactions": "Total Transactions",
    "dashboard.recentActivity": "Activité Récente des Utilisateurs",
    "dashboard.userGrowth": "Croissance des Utilisateurs",
    "dashboard.taskStats": "Statistiques des tâches",
    "dashboard.scheduledTasks": "Tâches planifiées",
    "dashboard.reservedTasks": "Tâches réservées",
    "dashboard.userStats": "Statistiques des utilisateurs",
    "dashboard.pendingUsers": "Utilisateurs en attente",
    "dashboard.verifiedUsers": "Utilisateurs vérifiés",
    "dashboard.usersRegisteredToday": "Utilisateurs inscrits aujourd'hui",
    "dashboard.usersRegisteredWeek": "Utilisateurs inscrits cette semaine",
    "dashboard.codeStats": "Statistiques des codes",
    "dashboard.pendingPasswordReset": "Réinitialisation du mot de passe en attente",
    "dashboard.pendingEmailVerification": "Vérification de l'email en attente",
    "dashboard.pendingPhoneVerification": "Vérification du téléphone en attente",
    "dashboard.notificationInfo": "Infos de notification",
    "dashboard.emailService": "Service Email",
    "dashboard.smsService": "Service SMS",
    "dashboard.asyncEnabled": "Async activé",
    "dashboard.loggingEnabled": "Journalisation activée",
    "dashboard.timestamp": "Horodatage",
    "dashboard.authError": "Erreur d'authentification",
    "dashboard.showOnlyActiveUsers": "Afficher uniquement les utilisateurs actifs",

    // Users
    "users.title": "Utilisateurs",
    "users.search": "Rechercher des utilisateurs...",
    "users.name": "Nom",
    "users.email": "Email",
    "users.status": "Statut",
    "users.createdAt": "Créé le",
    "users.active": "Actif",
    "users.inactive": "Inactif",
    "users.pending": "En attente",
    "users.allStatuses": "Tous les statuts",
    "users.phone": "Téléphone",
    "users.emailVerified": "Email vérifié",
    "users.phoneVerified": "Téléphone vérifié",
    "users.lastLogin": "Dernière connexion",
    "users.details": "Détails",
    "users.isActive": "Est actif",
    "users.uid": "UID",
    "users.verifyEmail": "Vérifier l'email",
    "users.verifyPhone": "Vérifier le téléphone",
    "users.contactMethod": "Méthode de contact",
    "users.viewType": "Type de vue",
    "users.pendingUsers": "Utilisateurs en attente",
    "users.allUsers": "Tous les utilisateurs",
    "users.showingResults": "Affichage de {start} à {end} sur {total} résultats",
    "users.pageOf": "Page {current} sur {total}",
    "users.sendCode": "Envoyer le code",
    "users.verifyCode": "Vérifier le code",
    "users.resendCode": "Renvoyer le code",
    "users.verificationCode": "Code de vérification",
    "users.enterVerificationCode": "Entrez le code de vérification",
    "users.codeSent": "Code envoyé avec succès",
    "users.verificationSuccess": "Vérification réussie",
    "users.enterIdentifierToSendCode": "Entrez le {type} pour envoyer le code de vérification",
    "users.enterCodeSentTo": "Entrez le code de vérification envoyé à {identifier}",
    "users.enterEmail": "Entrez l'email",
    "users.enterPhone": "Entrez le numéro de téléphone",
    "users.sending": "Envoi...",
    "users.verifying": "Vérification...",
    

    // Activation/Deactivation
    "users.activate": "Activer",
    "users.deactivate": "Désactiver",
    "users.activating": "Activation en cours...",
    "users.deactivating": "Désactivation en cours...",
    "users.activated": "Utilisateur activé",
    "users.deactivated": "Utilisateur désactivé",
    "users.activationFailed": "Échec de l'activation de l'utilisateur",
    "users.deactivationFailed": "Échec de la désactivation de l'utilisateur",
    "users.userActivatedSuccessfully": "Utilisateur activé avec succès",
    "users.userDeactivatedSuccessfully": "Utilisateur désactivé avec succès",
    // Verification toggle
    "users.unverifyEmail": "Annuler la vérification de l'email",
    "users.unverifyPhone": "Annuler la vérification du téléphone",
    "users.emailUnverifiedSuccessfully": "Email de l'utilisateur non vérifié avec succès",
    "users.phoneUnverifiedSuccessfully": "Téléphone de l'utilisateur non vérifié avec succès",
    "users.confirmVerifyEmail": "Êtes-vous sûr de vouloir vérifier l'email de cet utilisateur ?",
    "users.confirmUnverifyEmail": "Êtes-vous sûr de vouloir annuler la vérification de l'email de cet utilisateur ?",
    "users.confirmVerifyPhone": "Êtes-vous sûr de vouloir vérifier le téléphone de cet utilisateur ?",
    "users.confirmUnverifyPhone": "Êtes-vous sûr de vouloir annuler la vérification du téléphone de cet utilisateur ?",
    "users.confirmActivateTitle": "Activer l'utilisateur",
    "users.confirmDeactivateTitle": "Désactiver l'utilisateur",
    "users.confirmActivateText": "Êtes-vous sûr de vouloir activer l'utilisateur ?",
    "users.confirmDeactivateText": "Êtes-vous sûr de vouloir désactiver l'utilisateur ?",

    // Transactions
    "transactions.title": "Transactions",
    "transactions.amount": "Montant",
    "transactions.user": "Utilisateur",
    "transactions.date": "Date",
    "transactions.type": "Type",
    "transactions.status": "Statut",
    "transactions.deposit": "Dépôt",
    "transactions.withdrawal": "Retrait",
    "transactions.transfer": "Transfert",
    "transactions.completed": "Terminé",
    "transactions.pending": "En attente",
    "transactions.failed": "Échoué",
    "transactions.sentToUser": "Envoyé à l'utilisateur",
    "transactions.actions": "Actions",
    "transactions.searchByUser": "Rechercher par utilisateur...",
    "transactions.allStatuses": "Tous les statuts",
    "transactions.allTypes": "Tous les types",
    "transactions.noTransactionsFound": "Aucune transaction trouvée.",
    "transactions.edit": "Modifier",
    "transactions.delete": "Supprimer",
    "transactions.deleteTransaction": "Supprimer la transaction",
    "transactions.deleteConfirmation": "Êtes-vous sûr de vouloir supprimer cette transaction ? Cette action ne peut pas être annulée.",
    "transactions.cancel": "Annuler",
    "transactions.editTransaction": "Modifier la transaction",
    "transactions.updateTransactionDetails": "Mettez à jour les détails de la transaction ci-dessous.",
    "transactions.externalTransactionId": "ID de transaction externe",
    "transactions.balanceBefore": "Solde avant",
    "transactions.balanceAfter": "Solde après",
    "transactions.fees": "Frais",
    "transactions.confirmationMessage": "Message de confirmation",
    "transactions.rawSms": "SMS brut",
    "transactions.completedAt": "Terminé à",
    "transactions.errorMessage": "Message d'erreur",
    "transactions.saving": "Sauvegarde...",
    "transactions.saveChanges": "Sauvegarder les modifications",
    "transactions.failedToLoad": "Échec du chargement des transactions",
    "transactions.failedToUpdate": "Échec de la mise à jour de la transaction.",
    "transactions.failedToDelete": "Impossible de supprimer la transaction.",
    "transactions.transactionUpdated": "Transaction mise à jour",
    "transactions.transactionUpdatedSuccess": "La transaction a été mise à jour avec succès.",
    "transactions.transactionDeleted": "Transaction supprimée",
    "transactions.transactionDeletedSuccess": "La transaction a été supprimée avec succès.",
    "transactions.deleteFailed": "Échec de la suppression",
    "transactions.showingResults": "Affichage de {start} à {end} sur {total} résultats",
    "transactions.pageOf": "Page {current} sur {total}",
    "transactions.recipientName": "Nom du destinataire",
    "transactions.recipientPhone": "Téléphone du destinataire",
    "transactions.reference": "Référence",
    "transactions.network": "Réseau",
    "transactions.createdAt": "Créé le",

    // Common
    "common.previous": "Précédent",
    "common.next": "Suivant",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.actions": "Actions",
    "common.loading": "Chargement...",
    "common.yes": "Oui",
    "common.close": "Fermer",
    "common.cancel": "Annuler",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.all": "Tous",
    "common.ok": "OK",
    "common.save": "Enregistrer",
    "common.errorOccurred": "Une erreur s'est produite",
    "common.retry": "Réessayer",
    "common.retrying": "Nouvelle tentative...",
    "common.dismiss": "Fermer",

    // Registration Form
    "register.title": "Enregistrer un nouvel utilisateur",
    "register.firstName": "Prénom",
    "register.lastName": "Nom de famille",
    "register.email": "Email",
    "register.phone": "Téléphone",
    "register.password": "Mot de passe",
    "register.passwordConfirm": "Confirmer le mot de passe",
    "register.submit": "Enregistrer l'utilisateur",
    "register.success": "Utilisateur enregistré avec succès !",
    "register.failed": "Échec de l'enregistrement.",
    "register.passwordsNoMatch": "Les mots de passe ne correspondent pas.",
    "register.networkError": "Erreur réseau.",
    "register.registering": "Enregistrement...",

    // Network Config
    "networkConfig.title": "Configuration réseau",
    "networkConfig.list": "Liste des configurations réseau",
    "networkConfig.create": "Créer une configuration réseau",
    "networkConfig.edit": "Modifier la configuration réseau",
    "networkConfig.add": "Ajouter une configuration réseau",
    "networkConfig.networkName": "Nom du réseau",
    "networkConfig.status": "Statut",
    "networkConfig.ussdCommands": "Commandes USSD",
    "networkConfig.smsKeywords": "Mots-clés SMS",
    "networkConfig.errorKeywords": "Mots-clés d'erreur",
    "networkConfig.settings": "Paramètres",
    "networkConfig.actions": "Actions",
    "networkConfig.active": "Actif",
    "networkConfig.inactive": "Inactif",
    "networkConfig.editButton": "Modifier",
    "networkConfig.network": "Réseau",
    "networkConfig.selectNetwork": "Sélectionner un réseau",
    "networkConfig.balanceCommand": "Commande de solde",
    "networkConfig.depositCommand": "Commande de dépôt",
    "networkConfig.withdrawalCommand": "Commande de retrait",
    "networkConfig.balanceKeywords": "Mots-clés de solde (séparés par des virgules)",
    "networkConfig.depositKeywords": "Mots-clés de dépôt (séparés par des virgules)",
    "networkConfig.withdrawalKeywords": "Mots-clés de retrait (séparés par des virgules)",
    "networkConfig.errorKeywordsInput": "Mots-clés d'erreur (séparés par des virgules)",
    "networkConfig.customSettings": "Paramètres personnalisés",
    "networkConfig.timeout": "Délai d'attente (secondes)",
    "networkConfig.maxRetries": "Nombre maximum de tentatives",
    "networkConfig.autoConfirm": "Confirmation automatique",
    "networkConfig.maxRetriesLabel": "Nombre max de tentatives :",
    "networkConfig.timeoutLabel": "Délai d'attente :",
    "networkConfig.autoConfirmLabel": "Confirmation auto :",
    "networkConfig.creating": "Création...",
    "networkConfig.saving": "Sauvegarde...",
    "networkConfig.saveChanges": "Sauvegarder les modifications",
    "networkConfig.cancel": "Annuler",
    "networkConfig.failedToLoad": "Échec du chargement des configurations réseau",
    "networkConfig.failedToCreate": "Échec de la création de la configuration réseau",
    "networkConfig.failedToUpdate": "Échec de la mise à jour de la configuration réseau",
    "networkConfig.failedToLoadNetworks": "Échec du chargement des réseaux",
    "networkConfig.errorLoading": "Erreur lors du chargement des configurations réseau",

    // Country
    "country.title": "Pays",
    "country.list": "Liste des pays",
    "country.create": "Créer un pays",
    "country.edit": "Modifier le pays",
    "country.add": "Ajouter un pays",
    "country.name": "Nom",
    "country.code": "Code",
    "country.status": "Statut",
    "country.actions": "Actions",
    "country.active": "Actif",
    "country.inactive": "Inactif",
    "country.editButton": "Modifier",
    "country.failedToLoad": "Échec du chargement des pays",
    "country.failedToCreate": "Échec de la création du pays",
    "country.failedToUpdate": "Échec de la mise à jour du pays",
    "country.creating": "Création...",
    "country.saving": "Enregistrement...",
    "country.loading": "Chargement...",
    "country.errorLoading": "Erreur lors du chargement des pays",

    // Network
    "network.title": "Réseau",
    "network.list": "Liste des réseaux",
    "network.create": "Créer un réseau",
    "network.edit": "Modifier le réseau",
    "network.add": "Ajouter un réseau",
    "network.name": "Nom",
    "network.code": "Code",
    "network.country": "Pays",
    "network.status": "Statut",
    "network.actions": "Actions",
    "network.active": "Actif",
    "network.inactive": "Inactif",
    "network.editButton": "Modifier",
    "network.ussdBaseCode": "Code de base USSD",
    "network.selectCountry": "Sélectionner un pays",
    "network.creating": "Création...",
    "network.saving": "Sauvegarde...",
    "network.save": "Sauvegarder",
    "network.cancel": "Annuler",
    "network.failedToLoad": "Échec du chargement des réseaux",
    "network.failedToCreate": "Échec de la création du réseau",
    "network.failedToUpdate": "Échec de la mise à jour du réseau",
    "network.failedToLoadCountries": "Échec du chargement des pays",
    "network.loading": "Chargement...",
    "network.errorLoading": "Erreur lors du chargement des réseaux",

    // Devices
    "devices.title": "Appareils",
    "devices.list": "Liste des appareils",
    "devices.failedToLoad": "Échec du chargement des appareils",
    "devices.success": "Appareils chargés avec succès",
    "devices.loadedSuccessfully": "Appareils chargés avec succès",
    "devices.deviceId": "ID de l'appareil",
    "devices.name": "Nom",
    "devices.status": "Statut",
    "devices.lastSync": "Dernière synchronisation",
    "devices.actions": "Actions",
    "devices.noActionsAvailable": "Aucune action disponible",
    "devices.errorLoading": "Erreur lors du chargement des appareils",

    // Phone Numbers
    "phoneNumbers.title": "Numéros de téléphone",
    "phoneNumbers.list": "Liste des numéros de téléphone",
    "phoneNumbers.failedToLoad": "Échec du chargement des numéros de téléphone",
    "phoneNumbers.phoneNumber": "Numéro de téléphone",
    "phoneNumbers.network": "Réseau",
    "phoneNumbers.fullName": "Nom complet",
    "phoneNumbers.errorLoading": "Erreur lors du chargement des numéros de téléphone",

    // SMS Logs
    "smsLogs.title": "Journaux SMS",
    "smsLogs.list": "Liste des journaux SMS",
    "smsLogs.failedToLoad": "Échec du chargement des journaux SMS",
    "smsLogs.sender": "Expéditeur",
    "smsLogs.content": "Contenu",
    "smsLogs.receivedAt": "Reçu le",
    "smsLogs.type": "Type",
    "smsLogs.copy": "Copier",
    "smsLogs.copied": "Copié !",
    "smsLogs.errorLoading": "Erreur lors du chargement des journaux SMS",

    // FCM Logs
    "fcmLogs.title": "Journaux FCM",
    "fcmLogs.list": "Liste des journaux FCM",
    "fcmLogs.failedToLoad": "Échec du chargement des journaux FCM",
    "fcmLogs.messageTitle": "Titre",
    "fcmLogs.body": "Corps",
    "fcmLogs.deviceId": "ID de l'appareil",
    "fcmLogs.createdAt": "Créé le",
    "fcmLogs.copy": "Copier",
    "fcmLogs.copied": "Copié !",
    "fcmLogs.errorLoading": "Erreur lors du chargement des journaux FCM",

    // Remote Command
    "remoteCommand.title": "Commande à distance",
    "remoteCommand.create": "Créer une commande à distance",
    "remoteCommand.failedToCreate": "Échec de la création de la commande à distance",
    "remoteCommand.command": "Commande",
    "remoteCommand.deviceId": "ID de l'appareil",
    "remoteCommand.parameters": "Paramètres (JSON)",
    "remoteCommand.priority": "Priorité",
    "remoteCommand.sending": "Envoi...",
    "remoteCommand.sendCommand": "Envoyer la commande",
    "remoteCommand.parametersMustBeValidJson": "Les paramètres doivent être un JSON valide",
    "remoteCommand.commandSentSuccessfully": "Commande envoyée avec succès",
    "remoteCommand.selectDeviceId": "Sélectionnez un appareil",

    // Common additional
    "common.no": "Non",
    "common.failedToLoad": "Échec du chargement des données",
    "common.failedToCreate": "Échec de la création",
    "common.failedToUpdate": "Échec de la mise à jour",
    "common.failedToDelete": "Échec de la suppression",
  },
}

const initialState: LanguageProviderState = {
  language: "fr",
  setLanguage: () => null,
  t: () => "",
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("fr")

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key as keyof (typeof translations)["en"]] || key
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, String(value))
      })
    }
    return text
  }

  const value = {
    language,
    setLanguage,
    t,
  }

  return <LanguageProviderContext.Provider value={value}>{children}</LanguageProviderContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext)

  if (context === undefined) throw new Error("useLanguage must be used within a LanguageProvider")

  return context
}
